---
name: "Feature Branch"
on:
  push:
    branches:
      - "*" # matches every branch
      - "*/*" # matches every branch containing a single '/'
      - "!main" # excludes master
      - "!master" # excludes master

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source codes
        uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14.15
      - name: Test client with nexus3 instance
        env:
          NEXUS3_LICENSE_B64_ENCODED: ${{ secrets.NEXUS3_LICENSE_B64_ENCODED }}
        run: |
          cd scripts
          echo "${NEXUS3_LICENSE_B64_ENCODED}" | base64 -d > license.lic
          ./start-services.sh
          cd -
          make test
          cd scripts
          ./stop-services.sh


