on: [pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.15.x, 1.16.x, 1.17.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout source codes
        uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2.1.5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Test client with nexus3 instance
        env:
          NEXUS3_LICENSE_B64_ENCODED: ${{ secrets.NEXUS3_LICENSE_B64_ENCODED }}
          AZURE_STORAGE_ACCOUNT_KEY: ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}
        run: |
          cd scripts
          echo "${NEXUS3_LICENSE_B64_ENCODED}" | base64 -d > license.lic
          ./start-services.sh
          cd -
          if [[ -z ${AZURE_STORAGE_ACCOUNT_KEY} ]]; then export SKIP_AZURE_TESTS="true"; fi
          make test
          cd scripts
          ./stop-services.sh
